2017-07-19 16:13:46,285 ERROR [main] j.j.c.n.ServerConnection [ServerConnection.java:32] Couldn't connect to server
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_131]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_131]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_131]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_131]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_131]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_131]
	at java.net.Socket.<init>(Unknown Source) ~[na:1.8.0_131]
	at java.net.Socket.<init>(Unknown Source) ~[na:1.8.0_131]
	at jaims_development_studio.jaims.client.networking.ServerConnection.initConnection(ServerConnection.java:30) ~[classes/:na]
	at jaims_development_studio.jaims.client.logic.DatabaseManagement.<init>(DatabaseManagement.java:39) [classes/:na]
	at jaims_development_studio.jaims.client.logic.ClientMain.initProgram(ClientMain.java:24) [classes/:na]
	at jaims_development_studio.jaims.client.logic.ClientMain.<init>(ClientMain.java:19) [classes/:na]
	at jaims_development_studio.jaims.client.logic.ClientMain.main(ClientMain.java:15) [classes/:na]
