2017-07-18 22:25:18,540 ERROR [main] j.j.c.n.ServerConnection [ServerConnection.java:29] Couldn't connect to server
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_131]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_131]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_131]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_131]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_131]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_131]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_131]
	at java.net.Socket.<init>(Unknown Source) ~[na:1.8.0_131]
	at java.net.Socket.<init>(Unknown Source) ~[na:1.8.0_131]
	at jaims_development_studio.jaims.client.networking.ServerConnection.initConnection(ServerConnection.java:27) ~[classes/:na]
	at jaims_development_studio.jaims.client.logic.DatabaseManagement.<init>(DatabaseManagement.java:37) [classes/:na]
	at jaims_development_studio.jaims.client.logic.ClientMain.initProgram(ClientMain.java:23) [classes/:na]
	at jaims_development_studio.jaims.client.logic.ClientMain.<init>(ClientMain.java:19) [classes/:na]
	at jaims_development_studio.jaims.client.logic.ClientMain.main(ClientMain.java:15) [classes/:na]
2017-07-18 22:25:18,763 ERROR [Thread-1] j.j.c.l.DatabaseManagement [DatabaseManagement.java:45] Failed to connect to database!
java.sql.SQLException: Database lock acquisition failure: lockFile: org.hsqldb.persist.LockFile@dd3a2efa[file =C:\.lck, exists=false, locked=false, valid=false, ] method: openRAF reason: java.io.FileNotFoundException: C:\.lck (Zugriff verweigert)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
	at org.hsqldb.jdbc.JDBCConnection.<init>(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
	at org.hsqldb.jdbc.JDBCDriver.getConnection(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
	at org.hsqldb.jdbc.JDBCDriver.connect(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_131]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_131]
	at jaims_development_studio.jaims.client.logic.DatabaseManagement.tableExists(DatabaseManagement.java:43) [classes/:na]
	at jaims_development_studio.jaims.client.logic.DatabaseManagement.run(DatabaseManagement.java:141) [classes/:na]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_131]
Caused by: org.hsqldb.HsqlException: Database lock acquisition failure: lockFile: org.hsqldb.persist.LockFile@dd3a2efa[file =C:\.lck, exists=false, locked=false, valid=false, ] method: openRAF reason: java.io.FileNotFoundException: C:\.lck (Zugriff verweigert)
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
	at org.hsqldb.persist.LockFile.newLockFileLock(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
	at org.hsqldb.persist.Logger.acquireLock(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
	at org.hsqldb.persist.Logger.open(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
	at org.hsqldb.Database.reopen(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
	at org.hsqldb.Database.open(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
	at org.hsqldb.DatabaseManager.getDatabase(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
	at org.hsqldb.DatabaseManager.newSession(Unknown Source) ~[hsqldb-2.4.0.jar:2.4.0]
	... 8 common frames omitted
